name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # load nvm
            export PATH=$PATH:$HOME/.nvm/versions/node/v22.18.0/bin
            
            cd /home/ec2-user/Multiplayer-Tic-Tac-Toe
            git pull origin main

            # Start server with pm2
            pm2 delete multiplayer-tic-tac-toe
            pm2 start server.js --name multiplayer-tic-tac-toe
            pm2 save
